{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if $attribute.has_content}
    <p class="faw">{concat( '&#', $attribute.content.value )}</p>
{else}
    {'Not specified'|i18n( 'design/standard/content/datatype' )}
{/if}